//register constants
export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

//personal 
export const GET_PERSONAL_DATA = 'GET_PERSONAL_DATA';
export const GET_DATA_BYPROGRAM = 'GET_DATA_BYPROGRAM';

//admin
export const GET_FIRST_ADMINDATA = 'GET_FIRST_ADMINDATA';
export const GET_SECOND_ADMINDATA = 'GET_SECOND_ADMINDATA';
export const GET_THIRD_ADMINDATA = 'GET_THIRD_ADMINDATA';

//edit
export const EDIT_DEPARTMENT_DATA = 'EDIT_DEPARTMENT_DATA';
export const EDIT_SUBJECT_DATA = 'EDIT_SUBJECT_DATA';
export const EDIT_ACHIEVEMENT_DATA = 'EDIT_ACHIEVEMENT_DATA';
export const EDIT_ENROLLEE_DATA = 'EDIT_ENROLLEE_DATA';
export const EDIT_PROGRAM_DATA = 'EDIT_PROGRAM_DATA';