//register constants
export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

//personal 
export const GET_PERSONAL_DATA = 'GET_PERSONAL_DATA';
export const GET_DATA_BYPROGRAM = 'GET_DATA_BYPROGRAM';

//admin
export const GET_DEPARTMENT_DATA = 'GET_DEPARTMENT_DATA';
export const GET_SUBJECT_DATA = 'GET_SUBJECT_DATA';
export const GET_ACHIEVEMENT_DATA = 'GET_ACHIEVEMENT_DATA';
export const GET_ENROLLEE_DATA = 'GET_ENROLLEE_DATA';
export const GET_PROGRAMS_DATA = 'GET_PROGRAMS_DATA';

//edit
export const EDIT_DEPARTMENT_DATA = 'EDIT_DEPARTMENT_DATA';
export const EDIT_SUBJECT_DATA = 'EDIT_SUBJECT_DATA';
export const EDIT_ACHIEVEMENT_DATA = 'EDIT_ACHIEVEMENT_DATA';
export const EDIT_ENROLLEE_DATA = 'EDIT_ENROLLEE_DATA';
export const EDIT_PROGRAM_DATA = 'EDIT_PROGRAM_DATA';